version: '3'

services:
  daft:
    image: ghcr.io/mloberg/daft-bot:latest
    environment:
      DATABASE_URL: postgresql://postgres:secret@db/daft
      BOT_TOKEN: ${BOT_TOKEN}
      SECRET: ${SECRET}
      BOT_PREFIX: ${BOT_PREFIX:-_}
      DJ_ROLE: ${DJ_ROLE:-daft-dj}
    volumes:
      - ./music:/app/music

  app:
    image: ghcr.io/mloberg/daft-bot:latest
    environment:
      DATABASE_URL: postgresql://postgres:secret@db/daft
      BOT_TOKEN: ${BOT_TOKEN}
      SECRET: ${SECRET}
    command: npm run --silent server
    ports:
      - 53134:53134

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: daft
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
